In [1]:
# Dependencies
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import requests
from census import Census
from us import states

# Census API Key 
from config import census_key
c_2013 = Census(census_key, year=2013)
c_2014 = Census(census_key, year=2014)
c_2015 = Census(census_key, year=2015)
c_2016 = Census(census_key, year=2016)
c_2017 = Census(census_key, year=2017)

In [2]:
#Get census data for 2013
census_data_2013 = c_2013.acs5.get(("NAME", "B19013_001E", "B19301_001E", "B23025_002E", "B23025_007E", 
                          "C24010_007E", "C24010_008E", "C24010_043E", "C24010_044E", "B01003_001E",
                          "B25035_001E", "B25058_001E", "B25064_001E", "B25077_001E", "B25088_002E",
                          "B15003_017E", "B15003_018E", "B15003_021E", "B15003_022E", "B15003_023E",
                          "B15003_025E"), {'for': 'COUNTY:*'})
census_pd_2013 = pd.DataFrame(census_data_2013)

census_pd_2013 = census_pd_2013.rename(columns={"B19013_001E": "Income",
                                      "B19301_001E": "Income Per Capita",
                                      "B23025_002E": "Employed",
                                      "B23025_007E": "Unemployed",
                                      "C24010_007E": "Employment Male Computer Engineering and Science Occupations",
                                      "C24010_008E": "Employment Male Computer and Mathematical Occupations",
                                      "C24010_043E": "Employment Female Computer Engineering and Science Occupations",
                                      "C24010_044E": "Employment Female Computer and Mathematical Occupations",
                                      "B01003_001E": "Population",
                                      "B25035_001E": "Median House Construction Year",
                                      "B25058_001E": "Average Rent",
                                      "B25064_001E": "Average Cost of Rent plus Utilities",
                                      "B25077_001E": "Average Value of an Owner Occupied Home",
                                      "B25088_002E": "Average Monthly Housing Expense for a Homeowner with a Mortgage",
                                      "B15003_017E": "People with a High School Diploma",
                                      "B15003_018E": "People with a GED",
                                      "B15003_021E": "People with an Associates",
                                      "B15003_022E": "people with a Bachelors",
                                      "B15003_023E": "People with a Masters",
                                      "B15003_025E": "People with a Doctorate",                                  
                                      "NAME": "Name", 
                                      "COUNTY:*": "County"})

In [3]:
#Get census data for 2014
census_data_2014 = c_2014.acs5.get(("NAME", "B19013_001E", "B19301_001E", "B23025_002E", "B23025_007E", 
                          "C24010_007E", "C24010_008E", "C24010_043E", "C24010_044E", "B01003_001E",
                          "B25035_001E", "B25058_001E", "B25064_001E", "B25077_001E", "B25088_002E",
                          "B15003_017E", "B15003_018E", "B15003_021E", "B15003_022E", "B15003_023E",
                          "B15003_025E"), {'for': 'COUNTY:*'})
census_pd_2014 = pd.DataFrame(census_data_2014)

census_pd_2014 = census_pd_2014.rename(columns={"B19013_001E": "Income",
                                      "B19301_001E": "Income Per Capita",
                                      "B23025_002E": "Employed",
                                      "B23025_007E": "Unemployed",
                                      "C24010_007E": "Employment Male Computer Engineering and Science Occupations",
                                      "C24010_008E": "Employment Male Computer and Mathematical Occupations",
                                      "C24010_043E": "Employment Female Computer Engineering and Science Occupations",
                                      "C24010_044E": "Employment Female Computer and Mathematical Occupations",
                                      "B01003_001E": "Population",
                                      "B25035_001E": "Median House Construction Year",
                                      "B25058_001E": "Average Rent",
                                      "B25064_001E": "Average Cost of Rent plus Utilities",
                                      "B25077_001E": "Average Value of an Owner Occupied Home",
                                      "B25088_002E": "Average Monthly Housing Expense for a Homeowner with a Mortgage",
                                      "B15003_017E": "People with a High School Diploma",
                                      "B15003_018E": "People with a GED",
                                      "B15003_021E": "People with an Associates",
                                      "B15003_022E": "people with a Bachelors",
                                      "B15003_023E": "People with a Masters",
                                      "B15003_025E": "People with a Doctorate",                                  
                                      "NAME": "Name", 
                                      "COUNTY:*": "County"})

In [4]:
#Get census data for 2015
census_data_2015 = c_2015.acs5.get(("NAME", "B19013_001E", "B19301_001E", "B23025_002E", "B23025_007E", 
                          "C24010_007E", "C24010_008E", "C24010_043E", "C24010_044E", "B01003_001E",
                          "B25035_001E", "B25058_001E", "B25064_001E", "B25077_001E", "B25088_002E",
                          "B15003_017E", "B15003_018E", "B15003_021E", "B15003_022E", "B15003_023E",
                          "B15003_025E"), {'for': 'COUNTY:*'})
census_pd_2015 = pd.DataFrame(census_data_2015)

census_pd_2015 = census_pd_2015.rename(columns={"B19013_001E": "Income",
                                      "B19301_001E": "Income Per Capita",
                                      "B23025_002E": "Employed",
                                      "B23025_007E": "Unemployed",
                                      "C24010_007E": "Employment Male Computer Engineering and Science Occupations",
                                      "C24010_008E": "Employment Male Computer and Mathematical Occupations",
                                      "C24010_043E": "Employment Female Computer Engineering and Science Occupations",
                                      "C24010_044E": "Employment Female Computer and Mathematical Occupations",
                                      "B01003_001E": "Population",
                                      "B25035_001E": "Median House Construction Year",
                                      "B25058_001E": "Average Rent",
                                      "B25064_001E": "Average Cost of Rent plus Utilities",
                                      "B25077_001E": "Average Value of an Owner Occupied Home",
                                      "B25088_002E": "Average Monthly Housing Expense for a Homeowner with a Mortgage",
                                      "B15003_017E": "People with a High School Diploma",
                                      "B15003_018E": "People with a GED",
                                      "B15003_021E": "People with an Associates",
                                      "B15003_022E": "people with a Bachelors",
                                      "B15003_023E": "People with a Masters",
                                      "B15003_025E": "People with a Doctorate",                                  
                                      "NAME": "Name", 
                                      "COUNTY:*": "County"})

In [5]:
#Get census data for 2016
census_data_2016 = c_2016.acs5.get(("NAME", "B19013_001E", "B19301_001E", "B23025_002E", "B23025_007E", 
                          "C24010_007E", "C24010_008E", "C24010_043E", "C24010_044E", "B01003_001E",
                          "B25035_001E", "B25058_001E", "B25064_001E", "B25077_001E", "B25088_002E",
                          "B15003_017E", "B15003_018E", "B15003_021E", "B15003_022E", "B15003_023E",
                          "B15003_025E"), {'for': 'COUNTY:*'})
census_pd_2016 = pd.DataFrame(census_data_2016)

census_pd_2016 = census_pd_2016.rename(columns={"B19013_001E": "Income",
                                      "B19301_001E": "Income Per Capita",
                                      "B23025_002E": "Employed",
                                      "B23025_007E": "Unemployed",
                                      "C24010_007E": "Employment Male Computer Engineering and Science Occupations",
                                      "C24010_008E": "Employment Male Computer and Mathematical Occupations",
                                      "C24010_043E": "Employment Female Computer Engineering and Science Occupations",
                                      "C24010_044E": "Employment Female Computer and Mathematical Occupations",
                                      "B01003_001E": "Population",
                                      "B25035_001E": "Median House Construction Year",
                                      "B25058_001E": "Average Rent",
                                      "B25064_001E": "Average Cost of Rent plus Utilities",
                                      "B25077_001E": "Average Value of an Owner Occupied Home",
                                      "B25088_002E": "Average Monthly Housing Expense for a Homeowner with a Mortgage",
                                      "B15003_017E": "People with a High School Diploma",
                                      "B15003_018E": "People with a GED",
                                      "B15003_021E": "People with an Associates",
                                      "B15003_022E": "people with a Bachelors",
                                      "B15003_023E": "People with a Masters",
                                      "B15003_025E": "People with a Doctorate",                                  
                                      "NAME": "Name", 
                                      "COUNTY:*": "County"})

In [6]:
#Get census data for 2017
census_data_2017 = c_2017.acs5.get(("NAME", "B19013_001E", "B19301_001E", "B23025_002E", "B23025_007E", 
                          "C24010_007E", "C24010_008E", "C24010_043E", "C24010_044E", "B01003_001E",
                          "B25035_001E", "B25058_001E", "B25064_001E", "B25077_001E", "B25088_002E",
                          "B15003_017E", "B15003_018E", "B15003_021E", "B15003_022E", "B15003_023E",
                          "B15003_025E"), {'for': 'COUNTY:*'})
census_pd_2017 = pd.DataFrame(census_data_2017)

census_pd_2017 = census_pd_2017.rename(columns={"B19013_001E": "Income",
                                      "B19301_001E": "Income Per Capita",
                                      "B23025_002E": "Employed",
                                      "B23025_007E": "Unemployed",
                                      "C24010_007E": "Employment Male Computer Engineering and Science Occupations",
                                      "C24010_008E": "Employment Male Computer and Mathematical Occupations",
                                      "C24010_043E": "Employment Female Computer Engineering and Science Occupations",
                                      "C24010_044E": "Employment Female Computer and Mathematical Occupations",
                                      "B01003_001E": "Population",
                                      "B25035_001E": "Median House Construction Year",
                                      "B25058_001E": "Average Rent",
                                      "B25064_001E": "Average Cost of Rent plus Utilities",
                                      "B25077_001E": "Average Value of an Owner Occupied Home",
                                      "B25088_002E": "Average Monthly Housing Expense for a Homeowner with a Mortgage",
                                      "B15003_017E": "People with a High School Diploma",
                                      "B15003_018E": "People with a GED",
                                      "B15003_021E": "People with an Associates",
                                      "B15003_022E": "people with a Bachelors",
                                      "B15003_023E": "People with a Masters",
                                      "B15003_025E": "People with a Doctorate",                                  
                                      "NAME": "Name", 
                                      "COUNTY:*": "County"})

In [29]:
#Breakdown Data for each county in 2013
county_df_2013 = census_pd_2013.groupby(["Name"])  
seattle_county_df_2013 = county_df_2013.get_group("King County, Washington")
portland_county_df_2013 = county_df_2013.get_group("Multnomah County, Oregon")
san_jose_county_df_2013 = county_df_2013.get_group("Santa Clara County, California")
sacramento_county_df_2013 = county_df_2013.get_group("Sacramento County, California")
austin_county_df_2013 = county_df_2013.get_group("Travis County, Texas")
san_antonio_county_df_2013 = county_df_2013.get_group("Bexar County, Texas")

seattle_county_df_2013["City"] = "Seattle"
portland_county_df_2013["City"] = "Portland"
san_jose_county_df_2013["City"] = "San Jose"
sacramento_county_df_2013["City"] = "Sacramento"
austin_county_df_2013["City"] = "Austin"
san_antonio_county_df_2013["City"] = "San Antonio"
#Breakdown Data for each county in 2014
county_df_2014 = census_pd_2014.groupby(["Name"])  
seattle_county_df_2014 = county_df_2014.get_group("King County, Washington")
portland_county_df_2014 = county_df_2014.get_group("Multnomah County, Oregon")
san_jose_county_df_2014 = county_df_2014.get_group("Santa Clara County, California")
sacramento_county_df_2014 = county_df_2014.get_group("Sacramento County, California")
austin_county_df_2014 = county_df_2014.get_group("Travis County, Texas")
san_antonio_county_df_2014 = county_df_2014.get_group("Bexar County, Texas")

seattle_county_df_2014["City"] = "Seattle"
portland_county_df_2014["City"] = "Portland"
san_jose_county_df_2014["City"] = "San Jose"
sacramento_county_df_2014["City"] = "Sacramento"
austin_county_df_2014["City"] = "Austin"
san_antonio_county_df_2014["City"] = "San Antonio"
#Breakdown Data for each county in 2015
county_df_2015 = census_pd_2015.groupby(["Name"])  
seattle_county_df_2015 = county_df_2015.get_group("King County, Washington")
portland_county_df_2015 = county_df_2015.get_group("Multnomah County, Oregon")
san_jose_county_df_2015 = county_df_2015.get_group("Santa Clara County, California")
sacramento_county_df_2015 = county_df_2015.get_group("Sacramento County, California")
austin_county_df_2015 = county_df_2015.get_group("Travis County, Texas")
san_antonio_county_df_2015 = county_df_2015.get_group("Bexar County, Texas")

seattle_county_df_2015["City"] = "Seattle"
portland_county_df_2015["City"] = "Portland"
san_jose_county_df_2015["City"] = "San Jose"
sacramento_county_df_2015["City"] = "Sacramento"
austin_county_df_2015["City"] = "Austin"
san_antonio_county_df_2015["City"] = "San Antonio"
#Breakdown Data for each county in 2016
county_df_2016 = census_pd_2016.groupby(["Name"])  
seattle_county_df_2016 = county_df_2016.get_group("King County, Washington")
portland_county_df_2016 = county_df_2016.get_group("Multnomah County, Oregon")
san_jose_county_df_2016 = county_df_2016.get_group("Santa Clara County, California")
sacramento_county_df_2016 = county_df_2016.get_group("Sacramento County, California")
austin_county_df_2016 = county_df_2016.get_group("Travis County, Texas")
san_antonio_county_df_2016 = county_df_2016.get_group("Bexar County, Texas")

seattle_county_df_2016["City"] = "Seattle"
portland_county_df_2016["City"] = "Portland"
san_jose_county_df_2016["City"] = "San Jose"
sacramento_county_df_2016["City"] = "Sacramento"
austin_county_df_2016["City"] = "Austin"
san_antonio_county_df_2016["City"] = "San Antonio"
#Breakdown Data for each county in 2017
county_df_2017 = census_pd_2017.groupby(["Name"])  
seattle_county_df_2017 = county_df_2017.get_group("King County, Washington")
portland_county_df_2017 = county_df_2017.get_group("Multnomah County, Oregon")
san_jose_county_df_2017 = county_df_2017.get_group("Santa Clara County, California")
sacramento_county_df_2017 = county_df_2017.get_group("Sacramento County, California")
austin_county_df_2017 = county_df_2017.get_group("Travis County, Texas")
san_antonio_county_df_2017 = county_df_2017.get_group("Bexar County, Texas")

seattle_county_df_2017["City"] = "Seattle"
portland_county_df_2017["City"] = "Portland"
san_jose_county_df_2017["City"] = "San Jose"
sacramento_county_df_2017["City"] = "Sacramento"
austin_county_df_2017["City"] = "Austin"
san_antonio_county_df_2017["City"] = "San Antonio"

/anaconda3/envs/py36/lib/python3.6/site-packages/ipykernel_launcher.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  # Remove the CWD from sys.path while we load stuff.
/anaconda3/envs/py36/lib/python3.6/site-packages/ipykernel_launcher.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  # This is added back by InteractiveShellApp.init_path()
/anaconda3/envs/py36/lib/python3.6/site-packages/ipykernel_launcher.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if sys.path[0] == '':
/anaconda3/envs/py36/lib/python3.6/site-packages/ipykernel_launcher.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  del sys.path[0]
/anaconda3/envs/py36/lib/python3.6/site-packages/ipykernel_launcher.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

/anaconda3/envs/py36/lib/python3.6/site-packages/ipykernel_launcher.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  from ipykernel import kernelapp as app
/anaconda3/envs/py36/lib/python3.6/site-packages/ipykernel_launcher.py:25: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/anaconda3/envs/py36/lib/python3.6/site-packages/ipykernel_launcher.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/anaconda3/envs/py36/lib/python3.6/site-packages/ipykernel_launcher.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/anaconda3/envs/py36/lib/python3.6/site-packages/ipykernel_launcher.py:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/anaconda3/envs/py36/lib/python3.6/site-packages/ipykernel_launcher.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/anaconda3/envs/py36/lib/python3.6/site-packages/ipykernel_launcher.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/anaconda3/envs/py36/lib/python3.6/site-packages/ipykernel_launcher.py:40: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/anaconda3/envs/py36/lib/python3.6/site-packages/ipykernel_launcher.py:41: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/anaconda3/envs/py36/lib/python3.6/site-packages/ipykernel_launcher.py:42: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/anaconda3/envs/py36/lib/python3.6/site-packages/ipykernel_launcher.py:43: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/anaconda3/envs/py36/lib/python3.6/site-packages/ipykernel_launcher.py:44: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/anaconda3/envs/py36/lib/python3.6/site-packages/ipykernel_launcher.py:45: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/anaconda3/envs/py36/lib/python3.6/site-packages/ipykernel_launcher.py:55: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/anaconda3/envs/py36/lib/python3.6/site-packages/ipykernel_launcher.py:56: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/anaconda3/envs/py36/lib/python3.6/site-packages/ipykernel_launcher.py:57: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/anaconda3/envs/py36/lib/python3.6/site-packages/ipykernel_launcher.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/anaconda3/envs/py36/lib/python3.6/site-packages/ipykernel_launcher.py:59: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/anaconda3/envs/py36/lib/python3.6/site-packages/ipykernel_launcher.py:60: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

/anaconda3/envs/py36/lib/python3.6/site-packages/ipykernel_launcher.py:70: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/anaconda3/envs/py36/lib/python3.6/site-packages/ipykernel_launcher.py:71: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/anaconda3/envs/py36/lib/python3.6/site-packages/ipykernel_launcher.py:72: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/anaconda3/envs/py36/lib/python3.6/site-packages/ipykernel_launcher.py:73: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/anaconda3/envs/py36/lib/python3.6/site-packages/ipykernel_launcher.py:74: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/anaconda3/envs/py36/lib/python3.6/site-packages/ipykernel_launcher.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [28]:
#Merge county data frames for 2013
county_frames_13 = [seattle_county_df_2013, portland_county_df_2013, san_jose_county_df_2013, sacramento_county_df_2013,
                austin_county_df_2013, san_antonio_county_df_2013]
county_frames_df_2013 = pd.concat(county_frames_13)
county_frames_df_2013.to_csv("Output/county_data_2013.csv", encoding="utf-8", index=True)
county_frames_df_2013 = county_frames_df_2013.set_index("City")
county_frames_df_2013

,Population,People with a High School Diploma,People with a GED,People with an Associates,people with a Bachelors,People with a Masters,People with a Doctorate,Income,Income Per Capita,Employed,...,Average Cost of Rent plus Utilities,Average Value of an Owner Occupied Home,Average Monthly Housing Expense for a Homeowner with a Mortgage,Employment Male Computer Engineering and Science Occupations,Employment Male Computer and Mathematical Occupations,Employment Female Computer Engineering and Science Occupations,Employment Female Computer and Mathematical Occupations,Name,county,state
City,,,,,,,,,,,,,,,,,,,,,
Seattle,1974567.0,199692.0,34275.0,111211.0,400568.0,165514.0,30904.0,71811.0,39911.0,1119827.0,...,1131.0,377300.0,2254.0,96923.0,62167.0,29612.0,16126.0,"King County, Washington",033,53
Portland,747641.0,82460.0,18831.0,36860.0,127473.0,55313.0,9204.0,52511.0,30475.0,422693.0,...,913.0,271600.0,1758.0,18189.0,8801.0,7227.0,3173.0,"Multnomah County, Oregon",051,41
San Jose,1812208.0,169834.0,19695.0,87289.0,314485.0,180189.0,39545.0,91702.0,41513.0,958713.0,...,1566.0,645600.0,3048.0,111537.0,60828.0,33454.0,18150.0,"Santa Clara County, California",085,06
Sacramento,1435207.0,176751.0,27295.0,86055.0,174232.0,56896.0,9251.0,55064.0,26739.0,709121.0,...,1024.0,234200.0,1863.0,29948.0,15960.0,13425.0,8555.0,"Sacramento County, California",067,06
Austin,1063248.0,96045.0,20299.0,38527.0,196613.0,77558.0,14451.0,58025.0,33206.0,606970.0,...,988.0,219200.0,1765.0,39839.0,22754.0,12067.0,6589.0,"Travis County, Texas",453,48
San Antonio,1753238.0,220020.0,51790.0,79152.0,182721.0,72774.0,11137.0,50112.0,24253.0,875109.0,...,839.0,123700.0,1324.0,27089.0,15439.0,9106.0,5173.0,"Bexar County, Texas",029,48

In [30]:
#Merge county data frames for 2014
county_frames_14 = [seattle_county_df_2014, portland_county_df_2014, san_jose_county_df_2014, sacramento_county_df_2014,
                austin_county_df_2014, san_antonio_county_df_2014]
county_frames_df_2014 = pd.concat(county_frames_14)
county_frames_df_2014.to_csv("Output/county_data_2014.csv", encoding="utf-8", index=True)
county_frames_df_2014 = county_frames_df_2014.set_index("City")
county_frames_df_2014

,Population,People with a High School Diploma,People with a GED,People with an Associates,people with a Bachelors,People with a Masters,People with a Doctorate,Income,Income Per Capita,Employed,...,Average Cost of Rent plus Utilities,Average Value of an Owner Occupied Home,Average Monthly Housing Expense for a Homeowner with a Mortgage,Employment Male Computer Engineering and Science Occupations,Employment Male Computer and Mathematical Occupations,Employment Female Computer Engineering and Science Occupations,Employment Female Computer and Mathematical Occupations,Name,county,state
City,,,,,,,,,,,,,,,,,,,,,
Seattle,2008997.0,200235.0,34611.0,115126.0,410758.0,174711.0,31902.0,73035.0,40656.0,1134741.0,...,1161.0,376200.0,2226.0,99363.0,64776.0,29879.0,16810.0,"King County, Washington",033,53
Portland,757371.0,82674.0,18649.0,39991.0,131987.0,56951.0,9385.0,52845.0,31047.0,425719.0,...,941.0,270200.0,1748.0,18630.0,9060.0,7049.0,2918.0,"Multnomah County, Oregon",051,41
San Jose,1841569.0,171597.0,20714.0,88279.0,324301.0,189646.0,41452.0,93854.0,42666.0,975248.0,...,1637.0,664100.0,2996.0,117910.0,65650.0,35701.0,19972.0,"Santa Clara County, California",085,06
Sacramento,1450277.0,181461.0,27745.0,89887.0,176972.0,59253.0,10029.0,55615.0,27071.0,713921.0,...,1035.0,236500.0,1795.0,29927.0,16679.0,13379.0,8621.0,"Sacramento County, California",067,06
Austin,1092810.0,100668.0,21137.0,39512.0,204643.0,81253.0,16268.0,59620.0,33943.0,620528.0,...,1022.0,224600.0,1768.0,41692.0,24236.0,11889.0,6619.0,"Travis County, Texas",453,48
San Antonio,1789088.0,226424.0,52758.0,83728.0,189609.0,75131.0,11600.0,50867.0,24525.0,892696.0,...,862.0,126100.0,1331.0,28263.0,16330.0,9653.0,5354.0,"Bexar County, Texas",029,48

In [31]:
#Merge county data frames for 2015
county_frames_15 = [seattle_county_df_2015, portland_county_df_2015, san_jose_county_df_2015, sacramento_county_df_2015,
                austin_county_df_2015, san_antonio_county_df_2015]
county_frames_df_2015 = pd.concat(county_frames_15)
county_frames_df_2015.to_csv("Output/county_data_2015.csv", encoding="utf-8", index=True)
county_frames_df_2015 = county_frames_df_2015.set_index("City")
county_frames_df_2015

,Population,People with a High School Diploma,People with a GED,People with an Associates,people with a Bachelors,People with a Masters,People with a Doctorate,Income,Income Per Capita,Employed,...,Average Cost of Rent plus Utilities,Average Value of an Owner Occupied Home,Average Monthly Housing Expense for a Homeowner with a Mortgage,Employment Male Computer Engineering and Science Occupations,Employment Male Computer and Mathematical Occupations,Employment Female Computer Engineering and Science Occupations,Employment Female Computer and Mathematical Occupations,Name,county,state
City,,,,,,,,,,,,,,,,,,,,,
Seattle,2045756.0,200955.0,35340.0,118760.0,425117.0,183123.0,33019.0,75302.0,41664.0,1155495.0,...,1204.0,384300.0,2196.0,104002.0,69120.0,31318.0,17813.0,"King County, Washington",033,53
Portland,768418.0,82029.0,18646.0,40698.0,137230.0,61150.0,9951.0,54102.0,31544.0,432755.0,...,964.0,278300.0,1729.0,19817.0,9907.0,7542.0,3139.0,"Multnomah County, Oregon",051,41
San Jose,1868149.0,170779.0,21635.0,90475.0,330869.0,199599.0,43627.0,96310.0,43880.0,992372.0,...,1705.0,698600.0,2943.0,123134.0,70248.0,37398.0,21066.0,"Santa Clara County, California",085,06
Sacramento,1465832.0,186165.0,28279.0,92923.0,184008.0,61344.0,9891.0,55987.0,27315.0,720070.0,...,1036.0,248400.0,1739.0,31282.0,17254.0,13572.0,8606.0,"Sacramento County, California",067,06
Austin,1121645.0,105688.0,21293.0,41719.0,217271.0,86065.0,16481.0,61451.0,35168.0,638174.0,...,1054.0,237100.0,1749.0,44497.0,26434.0,13499.0,7393.0,"Travis County, Texas",453,48
San Antonio,1825502.0,234536.0,54475.0,86596.0,195958.0,77664.0,11703.0,51150.0,24735.0,908244.0,...,876.0,129400.0,1321.0,29193.0,16797.0,10106.0,5570.0,"Bexar County, Texas",029,48

In [32]:
#Merge county data frames for 2016
county_frames_16 = [seattle_county_df_2016, portland_county_df_2016, san_jose_county_df_2016, sacramento_county_df_2016,
                austin_county_df_2016, san_antonio_county_df_2016]
county_frames_df_2016 = pd.concat(county_frames_16)
county_frames_df_2016.to_csv("Output/county_data_2016.csv", encoding="utf-8", index=True)
county_frames_df_2016 = county_frames_df_2016.set_index("City")
county_frames_df_2016

,Population,People with a High School Diploma,People with a GED,People with an Associates,people with a Bachelors,People with a Masters,People with a Doctorate,Income,Income Per Capita,Employed,...,Average Cost of Rent plus Utilities,Average Value of an Owner Occupied Home,Average Monthly Housing Expense for a Homeowner with a Mortgage,Employment Male Computer Engineering and Science Occupations,Employment Male Computer and Mathematical Occupations,Employment Female Computer Engineering and Science Occupations,Employment Female Computer and Mathematical Occupations,Name,county,state
City,,,,,,,,,,,,,,,,,,,,,
Seattle,2079550.0,199511.0,34888.0,120434.0,441453.0,193995.0,35241.0,78800.0,43629.0,1175087.0,...,1273.0,407400.0,2211.0,110006.0,73216.0,33382.0,19024.0,"King County, Washington",033,53
Portland,778193.0,79064.0,19353.0,41502.0,144518.0,63821.0,10591.0,57449.0,33255.0,439447.0,...,1013.0,297300.0,1754.0,21867.0,11120.0,8101.0,3379.0,"Multnomah County, Oregon",051,41
San Jose,1885056.0,168399.0,21352.0,89726.0,342701.0,208794.0,44998.0,101173.0,46034.0,1005037.0,...,1813.0,752400.0,2972.0,130387.0,76508.0,40218.0,22764.0,"Santa Clara County, California",085,06
Sacramento,1479300.0,190520.0,28724.0,94393.0,189759.0,64859.0,9868.0,57509.0,28292.0,724073.0,...,1065.0,271300.0,1739.0,31512.0,16973.0,13769.0,8925.0,"Sacramento County, California",067,06
Austin,1148176.0,109416.0,21213.0,41932.0,227391.0,90355.0,16365.0,64422.0,36649.0,656559.0,...,1113.0,253600.0,1780.0,46004.0,27960.0,14306.0,8060.0,"Travis County, Texas",453,48
San Antonio,1858699.0,242242.0,54318.0,90734.0,201468.0,80858.0,12404.0,52353.0,25317.0,925592.0,...,902.0,134400.0,1333.0,29878.0,17327.0,9793.0,5619.0,"Bexar County, Texas",029,48

In [33]:
#Merge county data frames for 2017
county_frames_17 = [seattle_county_df_2017, portland_county_df_2017, san_jose_county_df_2017, sacramento_county_df_2017,
                austin_county_df_2017, san_antonio_county_df_2017]
county_frames_df_2017 = pd.concat(county_frames_17)
county_frames_df_2017.to_csv("Output/county_data_2017.csv", encoding="utf-8", index=True)
county_frames_df_2017 = county_frames_df_2017.set_index("City")
county_frames_df_2017

,Population,People with a High School Diploma,People with a GED,People with an Associates,people with a Bachelors,People with a Masters,People with a Doctorate,Income,Income Per Capita,Employed,...,Average Cost of Rent plus Utilities,Average Value of an Owner Occupied Home,Average Monthly Housing Expense for a Homeowner with a Mortgage,Employment Male Computer Engineering and Science Occupations,Employment Male Computer and Mathematical Occupations,Employment Female Computer Engineering and Science Occupations,Employment Female Computer and Mathematical Occupations,Name,county,state
City,,,,,,,,,,,,,,,,,,,,,
Seattle,2118119.0,197949.0,35229.0,122087.0,460158.0,207754.0,37018.0,83571.0,46316.0,1202593.0,...,1379.0,446600.0,2271.0,116677.0,78969.0,34354.0,19846.0,"King County, Washington",033,53
Portland,788459.0,79217.0,20542.0,42480.0,150503.0,67046.0,10973.0,60369.0,34848.0,446855.0,...,1094.0,330900.0,1799.0,22233.0,11363.0,8986.0,3915.0,"Multnomah County, Oregon",051,41
San Jose,1911226.0,172224.0,21547.0,89662.0,351778.0,220693.0,47562.0,106761.0,48689.0,1026078.0,...,1955.0,829600.0,3081.0,136646.0,82007.0,42697.0,24561.0,"Santa Clara County, California",085,06
Sacramento,1495400.0,195780.0,28365.0,96992.0,196514.0,67958.0,10702.0,60239.0,29693.0,732447.0,...,1122.0,299900.0,1781.0,33405.0,18424.0,14057.0,9097.0,"Sacramento County, California",067,06
Austin,1176584.0,114085.0,21586.0,44460.0,240380.0,96203.0,17028.0,68350.0,38820.0,676509.0,...,1172.0,275800.0,1851.0,49460.0,30173.0,14960.0,8613.0,"Travis County, Texas",453,48
San Antonio,1892004.0,248198.0,56207.0,93741.0,208782.0,84743.0,12814.0,53999.0,26158.0,940458.0,...,942.0,142300.0,1369.0,31804.0,18580.0,11004.0,6344.0,"Bexar County, Texas",029,48